# Caminhos dos diretórios de treino e teste
TRAIN_DIR: "/home/rodrigoduarte/Documentos/projeto/imagens/swedish/train"
TEST_DIR: "/home/rodrigoduarte/Documentos/projeto/imagens/swedish/test"
PROJECT: "swedish_no_ensemble_kf"
CHECKPOINT_PATH: "swedish_no_ensemble_kf_checkpoints_config_train2"
NAME_DATASET: "swedish"
WANDB_RUN_NAME: A

# Hiperparâmetros relacionados à configuração do modelo
TMODEL: "swint_t"
SHAPE: [224, 224]
FEATURES_DIM: 648
HIDDEN_LAYERS: 2
HIDDEN_UNITS: 1296
MAX_EPOCHS: 50
NUM_CLASSES: 44
BATCH_SIZE: 64
LEARNING_RATE: 0.000046341
SCALE_FACTOR: 0.8
DROP_PATH_RATE: 0.30621
LABEL_SMOOTHING: 0.049964
OPTIMIZER_MOMENTUM: [0.9, 0.95618]
WEIGHT_DECAY: 9.3116e-7
LAYER_SCALE: 1.47315
MLP_VECTOR_MODEL_SCALE: 0.76484
K_FOLDS: 5

# Configurações de hardware e execução
NUM_WORKERS: 4
ACCELERATOR: "gpu"
DEVICES: [1]
PRECISION: "16-mixed"