# Caminhos dos diretórios de treino e teste
TRAIN_DIR: "/home/rodrigoduarte/Documentos/projeto/imagens/D2/train"
TEST_DIR: "/home/rodrigoduarte/Documentos/projeto/imagens/D2/test"
PROJECT: "D2_ensemble_kf"
CHECKPOINT_PATH: "D2_ensemble_kf_checkpoints_config_train"
NAME_DATASET: "D2"
BEST_MODEL_PATH: /Documentos/projeto/D2_bestmodel/visionary-sweep-2/best_model.ckpt
RUN_NAME: visionary-sweep-2
CM_PATH: /home/rodrigoduarte/Documentos/projeto/matriz_de_confusao


# Hiperparâmetros relacionados à configuração do modelo
TMODEL: "swint_t"
SHAPE: [224, 224]
FEATURES_DIM: 648
HIDDEN_LAYERS: 2
HIDDEN_UNITS: 1296
MAX_EPOCHS: 50
NUM_CLASSES: 44
BATCH_SIZE: 64
LEARNING_RATE: 0.00018973
SCALE_FACTOR: 0.8
DROP_PATH_RATE: 0.30621
LABEL_SMOOTHING: 0.0010509
OPTIMIZER_MOMENTUM: 0.93112
WEIGHT_DECAY: 4.4776e-7
LAYER_SCALE: 1.20865
MLP_VECTOR_MODEL_SCALE: 0.99277
K_FOLDS: 5

# Configurações de hardware e execução
NUM_WORKERS: 4
ACCELERATOR: "gpu"
DEVICES: [1]
PRECISION: "16-mixed"