# Caminhos dos diretórios de treino e teste
TRAIN_DIR: "/home/rodrigoduarte/Documentos/projeto/imagens/flavia/train"
TEST_DIR: "/home/rodrigoduarte/Documentos/projeto/imagens/flavia/test"
PROJECT: "flavia_t_ensemble"
CHECKPOINT_PATH: "checkpoints_config2"
BEST_CHECKPOINT_PATH: "/home/rodrigoduarte/Documentos/projeto/checkpoints_config/epochepoch=99-val_lossval_loss=0.67.ckpt"
NAME_DATASET: "flavia"

# Hiperparâmetros relacionados à configuração do modelo
TMODEL: "cct_224"
SHAPE: [224, 224]
FEATURES_DIM: 648
HIDDEN_LAYERS: 2
HIDDEN_UNITS: 1296
MAX_EPOCHS: 50
NUM_CLASSES: 32
BATCH_SIZE: 32  # Valor padrão (será sobrescrito pelo sweep)
LEARNING_RATE: 6e-5  # Valor padrão (será sobrescrito pelo sweep)
OPTIMIZER_MOMENTUM: [0.9, 0.999]
SCALE_FACTOR: 0.8
DROP_PATH_RATE: 0.1
LABEL_SMOOTHING: 0.1
WEIGHT_DECAY: 0.05
LAYER_SCALE: 0.85
MLP_VECTOR_MODEL_SCALE: 2

# Configurações de hardware e execução
NUM_WORKERS: 4
ACCELERATOR: "gpu"
DEVICES: [1]
PRECISION: "16-mixed"