# Caminhos dos diretórios de treino e teste
TRAIN_DIR: "/home/rodrigoduarte/Documentos/projeto/imagens/flavia/train"
TEST_DIR: "/home/rodrigoduarte/Documentos/projeto/imagens/flavia/test"
PROJECT: "flavia_kf"
CHECKPOINT_PATH: "flavia_ensemble_kf_checkpoints_config_train"
NAME_DATASET: "flavia"
BEST_MODEL_PATH: /Documentos/projeto/flavia_bestmodel/visionary-sweep-2/best_model.ckpt
RUN_NAME: visionary-sweep-2
CM_PATH: /home/rodrigoduarte/Documentos/projeto/matriz_de_confusao


# Hiperparâmetros relacionados à configuração do modelo
TMODEL: "convnext_t"
SHAPE: [224, 224]
FEATURES_DIM: 648
HIDDEN_LAYERS: 2
HIDDEN_UNITS: 1296
SCALE_FACTOR: 0.8
MAX_EPOCHS: 100 # Número de épocas por fold
NUM_CLASSES: 32 #IMPORTANTE NAO ESQUECER DE MUDAR
BATCH_SIZE: 64 
LEARNING_RATE: 0.000018744
DROP_PATH_RATE: 0.039083
LABEL_SMOOTHING: 0.00085622
OPTIMIZER_MOMENTUM: 0.92921
WEIGHT_DECAY: 0.00085839
LAYER_SCALE: 2.72562
MLP_VECTOR_MODEL_SCALE: 0.97399
K_FOLDS: 5  # Número de folds na validação cruzada

# Configurações de hardware e execução
NUM_WORKERS: 4
ACCELERATOR: "gpu"
DEVICES: [0]
PRECISION: "16-mixed"