# Caminhos dos diretórios de treino e teste
TRAIN_DIR: "/home/rodrigoduarte/Documentos/projeto/imagens/D2/train"
TEST_DIR: "/home/rodrigoduarte/Documentos/projeto/imagens/D2/test"
PROJECT: "D2_ensemble_kf_final"
CHECKPOINT_PATH: "D2_checkpoints_config"
NAME_DATASET: "D2"
BEST_MODEL_PATH: /Documentos/projeto/D2_bestmodel/spring-sweep-38/best_model.ckpt
RUN_NAME: spring-sweep-38
CM_PATH: /home/rodrigoduarte/Documentos/projeto/matriz_de_confusao


# Hiperparâmetros relacionados à configuração do modelo
TMODEL: "convnext_t"
SHAPE: [224, 224]
FEATURES_DIM: 648
HIDDEN_LAYERS: 2
HIDDEN_UNITS: 1296
MAX_EPOCHS: 40  # Número de épocas por fold
NUM_CLASSES: 44
BATCH_SIZE: 32  
LEARNING_RATE: 0.000097993  
SCALE_FACTOR: 0.8
DROP_PATH_RATE: 0.40165
LABEL_SMOOTHING: 0.18968
OPTIMIZER_MOMENTUM: [0.9, 0.88456]
WEIGHT_DECAY: 2.1733e-7
LAYER_SCALE: 0.5816
MLP_VECTOR_MODEL_SCALE: 0.93104
K_FOLDS: 5  # Número de folds na validação cruzada

# Configurações de hardware e execução
NUM_WORKERS: 4
ACCELERATOR: "gpu"
DEVICES: [0]
PRECISION: "16-mixed"