# Caminhos dos diretórios de treino e teste
TRAIN_DIR: "/home/rodrigoduarte/Documentos/projeto/imagens/swedish/train"
TEST_DIR: "/home/rodrigoduarte/Documentos/projeto/imagens/swedish/test"
PROJECT: "swedish_ensemble_kf"
CHECKPOINT_PATH: "swedish_ensemble_kf_checkpoints_config_train"
NAME_DATASET: "swedish"
BEST_MODEL_PATH: /Documentos/projeto/swedish_bestmodel/visionary-sweep-2/best_model.ckpt
RUN_NAME: visionary-sweep-2
CM_PATH: /home/rodrigoduarte/Documentos/projeto/matriz_de_confusao


# Hiperparâmetros relacionados à configuração do modelo
TMODEL: "swint_t"
SHAPE: [224, 224]
FEATURES_DIM: 648
HIDDEN_LAYERS: 2
HIDDEN_UNITS: 1296
MAX_EPOCHS: 100
NUM_CLASSES: 15
BATCH_SIZE: 64
LEARNING_RATE: 0.000044942
SCALE_FACTOR: 0.8
DROP_PATH_RATE: 0.05316
LABEL_SMOOTHING: 0.021871
OPTIMIZER_MOMENTUM: 0.94779
WEIGHT_DECAY: 0.000090261
LAYER_SCALE: 2.75512
MLP_VECTOR_MODEL_SCALE: 1.16084
K_FOLDS: 5

# Configurações de hardware e execução
NUM_WORKERS: 4
ACCELERATOR: "gpu"
DEVICES: [1]
PRECISION: "16-mixed"