# Caminhos dos diretórios de treino e teste
TRAIN_DIR: "/home/rodrigoduarte/Documentos/projeto/imagens/swedish/train"
TEST_DIR: "/home/rodrigoduarte/Documentos/projeto/imagens/swedish/test"
PROJECT: "swedish_kf"
CHECKPOINT_PATH: "swedish_ensemble_kf_checkpoints_config_train"
NAME_DATASET: "swedish"
BEST_MODEL_PATH: /Documentos/projeto/swedish_bestmodel/visionary-sweep-2/best_model.ckpt
RUN_NAME: visionary-sweep-2
CM_PATH: /home/rodrigoduarte/Documentos/projeto/matriz_de_confusao


# Hiperparâmetros relacionados à configuração do modelo
TMODEL: "convnext_t"
SHAPE: [224, 224]
FEATURES_DIM: 648
HIDDEN_LAYERS: 2
HIDDEN_UNITS: 1296
SCALE_FACTOR: 0.8
MAX_EPOCHS: 100  # Número de épocas por fold
NUM_CLASSES: 15 #IMPORTANTE NAO ESQUECER DE MUDAR
BATCH_SIZE: 64 
LEARNING_RATE: 0.000073994
DROP_PATH_RATE: 0.3639
LABEL_SMOOTHING: 0.0099383
OPTIMIZER_MOMENTUM: 0.97446
WEIGHT_DECAY: 0.00011757
LAYER_SCALE: 2.93919
MLP_VECTOR_MODEL_SCALE: 1.07586
K_FOLDS: 5  # Número de folds na validação cruzada

# Configurações de hardware e execução
NUM_WORKERS: 4
ACCELERATOR: "gpu"
DEVICES: [0]
PRECISION: "16-mixed"