# Caminhos dos diretórios de treino e teste
ROOT_DIR: "imagens_csv/swedish"
TRAIN_DIR: "imagens/swedish/train"
TRAIN_CSV_DIR: "imagens_csv/swedish/train"
TEST_CSV_DIR: "imagens_csv/swedish/test"  # Corrigido aqui
TEST_DIR: "imagens/swedish/test"
PROJECT: "swedish_convnext_s_224"

# Hiperparâmetros relacionados à configuração do modelo
SHAPE: [224, 224]
INPUT_NETWORK: 432
HIDDEN_LAYERS: 2
HIDDEN_UNITS: 864
MAX_EPOCHS: 1000
NUM_CLASSES: 15
BATCH_SIZE: 8  # Valor padrão (será sobrescrito pelo sweep)
LEARNING_RATE: 5e-5  # Valor padrão (será sobrescrito pelo sweep)
WEIGHT_DECAY: 1e-8
OPTIMIZER_MOMENTUM: [0.9, 0.999]
SCALE_FACTOR: 0.8
DROP_PATH_RATE: 0.1
LABEL_SMOOTHING: 0.1
WEIGHT_DECAY: 0.05

# Configurações de hardware e execução
NUM_WORKERS: 4
ACCELERATOR: "gpu"
DEVICES: [0]
PRECISION: "16-mixed"