# Caminhos dos diretórios de treino e teste
TRAIN_DIR: "/home/rodrigoduarte/Documentos/projeto/imagens/D2/train"
TEST_DIR: "/home/rodrigoduarte/Documentos/projeto/imagens/D2/test"
PROJECT: "D2_vec_seeds"
CHECKPOINT_PATH: "D2_vec_seeds_checkpoints_config_train"
NAME_DATASET: "D2"
BEST_MODEL_PATH: /Documentos/projeto/D2_bestmodel/visionary-sweep-2/best_model.ckpt
RUN_NAME: stilted-sweep-13
CM_PATH: /home/rodrigoduarte/Documentos/projeto/matriz_de_confusao

# Hiperparâmetros relacionados à configuração do modelo
TMODEL: "vector"
SHAPE: [224, 224]
FEATURES_DIM: 648
HIDDEN_LAYERS: 2
HIDDEN_UNITS: 648
MAX_EPOCHS: 50
NUM_CLASSES: 44
BATCH_SIZE: 64


DROP_PATH_RATE: 0.10          # antes: 0.049964
LABEL_SMOOTHING: 0.10         # antes: 0.049964
LAYER_SCALE: 1.47315
LEARNING_RATE: 0.000046342         # antes: 0.000046342
OPTIMIZER_MOMENTUM: 0.93113
WEIGHT_DECAY: 4.4777e-7            # antes: 4.4777e-7

K_FOLDS: 5
N_SEEDS: 10


USE_WEIGHTED_SAMPLER: true     # mantém amostragem balanceada
SAMPLER_REPLACEMENT: true
USE_CLASS_WEIGHTS: false       # desativa pesos na loss para evitar supercompensação
WEIGHT_MODE: inv_freq
CB_BETA: 0.9999

# Configurações de hardware e execução
NUM_WORKERS: 4
ACCELERATOR: "gpu"
DEVICES: [0]
PRECISION: "16-mixed"
